class Constants(object):
    CONFIG_FILE_NAME = 'config.ini'
    DEFAULT_CONFIG_FILE_NAME = 'default_config.ini'
    CONFIG_SECTION_GLOBAL = 'Global'
    CONFIG_OPTION_ACTIVE_USER = 'ActiveUser'
    CONFIG_OPTION_ACTIVE_MODE = 'ActiveMode'
    CONFIG_USERNAME_PREFIX = 'User_'
    CONFIG_OPTION_PASSWORD_PREFIX = 'Password_'
    USERNAME_MIN_LENGTH = 1
    USERNAME_MAX_LENGTH = 10
    SESSION_ITERATIONS = 3  
    SESSION_FILE_DATETIME_FORMAT = '%Y-%m-%d-%H-%M-%S'
